version: '3'

services:
  postgres:
    image: postgres
    volumes:
    - ./volumes/database:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: fisiopar
      POSTGRES_PASSWORD: ads@00
      POSTGRES_DB: fisiopar